name: '[PREPROD] UKMCAB e2e tests'
run-name: PREPROD e2e test suite initiated by ${{ github.actor }} 🚀
on: workflow_dispatch
jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create cypress.env.json with secret config values stored in Github
        run: |
          echo '${{ secrets.PREPROD_CONFIG }}' > cypress.env.json
      - name: Cypress Run
        uses: cypress-io/github-action@v5.0.2
        with:
          browser: chrome
          config: baseUrl=https://ukmcab-pp.beis.gov.uk