name: "[STAGE] UKMCAB e2e tests"
run-name: ${{ github.actor }} is running GitHub Actions for UKMCAB e2e tests 🚀
on:
  push:
    branches:
      - 'ci-env-test'
jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create cypress.env.json with secret config values stored in Github
        run: |
          echo '${{ secrets.STAGE_CONFIG }}' > cypress.env.json
      - name: Cypress Run
        uses: cypress-io/github-action@v5.0.2
        with:
          browser: chrome
          config: baseUrl=https://ukmcab-stage.beis.gov.uk